# Generated by Django 5.0.1 on 2024-01-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihalar', '0002_lessees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
